spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

    eureka:
        client:
            service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true
server:
  port: 8082
